// Re-exportar tipos desde el archivo principal de tipos
export type {
  Notification,
  NotificationTag,
  NotificationContext,
  NotificationAIRecommendation as AIRecommendation,
  QuickAction,
  TimelineEvent,
  RelatedLink,
  NotificationIconType,
  NotificationFilters,
  NotificationStats,
  NotificationModuleSettings as NotificationSettings,
  NotificationState,
  NotificationAction,
  NotificationAPIResponse,
  NotificationWebSocketEvent,
  NotificationExportOptions,
  NotificationSearchQuery,
  NotificationGroup,
  NotificationSortField,
  NotificationSortOrder,
  NotificationSortOptions,
  NotificationPagination,
  NotificationPaginatedResponse,
  NotificationBulkAction,
  NotificationTemplate,
  NotificationRule,
  NotificationRuleCondition,
  NotificationRuleAction,
  NotificationMetrics,
  NotificationIntegration,
  NotificationAuditLog
} from '../../../types/notification'; 