export { default as HRModule } from './HRModule';
export { EmployeeList } from './components/EmployeeList';
export { EmployeeDetail } from './components/EmployeeDetail';
export { HRDashboard } from './components/HRDashboard';
export { PayrollModule } from './components/PayrollModule';
export { TalentModule } from './components/TalentModule';
export { RecruitmentModule } from './components/RecruitmentModule';
export { AnalyticsModule } from './components/AnalyticsModule';
export { ComplianceModule } from './components/ComplianceModule';
export { HRCopilot } from './components/HRCopilot';